INSERT INTO cursos ( ID, Nombre, Profesor ) VALUES (1, 'Matemáticas', 'Dr. García');
INSERT INTO cursos ( ID, Nombre, Profesor ) VALUES (2, 'Historia', 'Prof. Martínez');
INSERT INTO cursos ( ID, Nombre, Profesor ) VALUES (3, 'Ciencias', 'Dr. Sánchez');
INSERT INTO cursos ( ID, Nombre, Profesor ) VALUES (4, 'Inglés', 'Prof. González');
INSERT INTO cursos ( ID, Nombre, Profesor ) VALUES (5, 'Geografía', 'Dr. Ramírez');
INSERT INTO estudiantes ( ID, Nombre, Apellido, Edad ) VALUES (1, 'Juan', 'Pérez', 20);
INSERT INTO estudiantes ( ID, Nombre, Apellido, Edad ) VALUES (2, 'María', 'Gómez', 22);
INSERT INTO estudiantes ( ID, Nombre, Apellido, Edad ) VALUES (3, 'Pedro', 'Rodríguez', 21);
INSERT INTO estudiantes ( ID, Nombre, Apellido, Edad ) VALUES (4, 'Ana', 'López', 23);
INSERT INTO estudiantes ( ID, Nombre, Apellido, Edad ) VALUES (5, 'Carlos', 'Martínez', 25);
INSERT INTO inscripcion ( ID, ID_Estudiante, ID_Curso ) VALUES (1, 1, 1);
INSERT INTO inscripcion ( ID, ID_Estudiante, ID_Curso ) VALUES (2, 1, 3);
INSERT INTO inscripcion ( ID, ID_Estudiante, ID_Curso ) VALUES (3, 2, 2);
INSERT INTO inscripcion ( ID, ID_Estudiante, ID_Curso ) VALUES (4, 3, 1);
INSERT INTO inscripcion ( ID, ID_Estudiante, ID_Curso ) VALUES (5, 4, 3);
INSERT INTO inscripcion ( ID, ID_Estudiante, ID_Curso ) VALUES (6, 5, 2);
INSERT INTO inscripcion ( ID, ID_Estudiante, ID_Curso ) VALUES (7, 2, 4);
INSERT INTO inscripcion ( ID, ID_Estudiante, ID_Curso ) VALUES (8, 4, 5);
